name: epiGBS
channels:
- conda-forge
- bioconda
- defaults
- r
dependencies:
- bcftools=1.3.1=1
- bioconductor-biobase=2.36.2=r3.4.1_0
- bioconductor-biocgenerics=0.24.0=r3.4.1_0
- bioconductor-biocparallel=1.12.0=r3.4.1_0
- bioconductor-biostrings=2.44.2=r3.4.1_0
- bioconductor-bsgenome=1.44.2=r3.4.1_0
- bioconductor-delayedarray=0.2.7=0
- bioconductor-genomeinfodb=1.12.3=r3.4.1_0
- bioconductor-genomeinfodbdata=0.99.1=r3.4.1_0
- bioconductor-genomicalignments=1.12.2=r3.4.1_0
- bioconductor-genomicranges=1.28.6=r3.4.1_0
- bioconductor-iranges=2.12.0=r3.4.1_0
- bioconductor-rsamtools=1.28.0=r3.4.1_0
- bioconductor-rtracklayer=1.36.6=0
- bioconductor-s4vectors=0.16.0=r3.4.1_0
- bioconductor-summarizedexperiment=1.6.5=r3.4.1_0
- bioconductor-xvector=0.16.0=r3.4.1_0
- bioconductor-zlibbioc=1.24.0=r3.4.1_0
- blat=35=1
- bwa=0.7.16=pl5.22.0_0
- pear=0.9.6=2
- sambamba=0.6.6=0
- samtools=1.3.1=5
- seqtk=1.2=0
- star=2.5.3a=0
- tabix=0.2.5=0
- vsearch=2.5.0=0
- bzip2=1.0.6=1
- ca-certificates=2017.7.27.1=0
- cairo=1.14.6=4
- certifi=2017.7.27.1=py27_0
- curl=7.54.1=0
- fontconfig=2.12.1=4
- freetype=2.7=1
- gettext=0.19.7=1
- glib=2.51.4=0
- graphite2=1.3.9=0
- gsl=2.1=2
- harfbuzz=1.4.3=0
- icu=58.1=1
- jpeg=9b=2
- krb5=1.14.2=0
- libffi=3.2.1=3
- libiconv=1.14=4
- libpng=1.6.28=1
- libssh2=1.8.0=1
- libtiff=4.0.7=0
- libxml2=2.9.5=0
- ncurses=5.9=10
- openssl=1.0.2l=0
- pango=1.40.4=0
- pcre=8.39=0
- perl=5.22.0.1=0
- pip=9.0.1=py27_0
- pixman=0.34.0=0
- python=2.7.14=0
- r-base=3.4.1=0
- r-bh=1.62.0_1=r3.4.1_0
- r-bitops=1.0_6=r3.4.1_0
- r-futile.logger=1.4.3=r3.4.1_0
- r-futile.options=1.0.0=r3.4.1_0
- r-lambda.r=1.1.9=r3.4.1_0
- r-lattice=0.20_34=r3.4.1_0
- r-matrix=1.2_7.1=r3.4.1_0
- r-matrixstats=0.52.2=r3.4.1_0
- r-rcurl=1.95_4.8=r3.4.1_0
- r-snow=0.4_2=r3.4.1_0
- r-xml=3.98_1.6=r3.4.1_0
- readline=6.2=0
- setuptools=36.6.0=py27_1
- sqlite=3.13.0=1
- tk=8.5.19=2
- wheel=0.30.0=py_1
- xz=5.2.3=0
- zlib=1.2.8=3
- libgcc=5.2.0=0
- wget=1.18=0
- pip:
  - backports.functools-lru-cache==1.4
  - backports.unittest-mock==1.3
  - biom-format==2.1.6
  - biopython==1.68
  - chardet==3.0.4
  - click==6.7
  - cycler==0.10.0
  - decorator==4.1.2
  - funcsigs==1.0.2
  - functools32==3.2.3.post2
  - future==0.16.0
  - genesis-pyapi==1.2.0
  - idna==2.6
  - matplotlib==2.0.0
  - matplotlib-venn==0.11.5
  - mock==2.0.0
  - nested-dict==1.61
  - networkx==2.0
  - numpy==1.12.0
  - orange-bioinformatics==2.6.22
  - pandas==0.20.3
  - pbr==3.1.1
  - pyfaidx==0.4.8.1
  - pygraphviz==1.3.1
  - pyparsing==2.2.0
  - pyqi==0.3.2
  - pysam==0.10.0
  - python-dateutil==2.6.1
  - python-levenshtein==0.12.0
  - pytz==2017.2
  - pyvcf==0.6.8
  - requests==2.18.4
  - requests-cache==0.4.13
  - scipy==0.18.1
  - seqenv==1.3.0
  - serverfiles==0.2.1
  - sh==1.12.14
  - singledispatch==3.4.0.3
  - six==1.11.0
  - slumber==0.7.1
  - sphinx-rtd-theme==0.1.10a0
  - subprocess32==3.2.7
  - toolshed==0.4.6
  - tqdm==4.19.4
  - typing==3.6.2
  - urllib3==1.22
